# Generated by Django 4.2.22 on 2025-08-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(db_table='app_shop_product_category', to='app_shop.productcategory'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='app_shop_product',
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='app_shop_category',
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='app_shop_product_image',
        ),
    ]
