# Generated by Django 4.2.22 on 2025-10-06 15:53

import app_account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[app_account.validators.CustomValidations.validate_phone_number]),
        ),
    ]
