# Generated by Django 4.2.22 on 2025-08-25 22:24

import app_account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('phone', models.CharField(max_length=11, validators=[app_account.validators.CustomValidations.validate_phone_number])),
                ('status', models.IntegerField(choices=[(1, 'جدید'), (2, 'خوانده شده'), (3, 'پاسخ داده شده')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'db_table': 'app_website_contact',
                'ordering': ['-created_date'],
            },
        ),
    ]
