# Generated by Django 4.2.22 on 2025-08-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_website_newsletter',
                'ordering': ['-created_date'],
            },
        ),
    ]
